spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: ''
    mode: LEGACYHTML5

logging:
  level:
    org:
      springframework:
        security: INFO
        web:      INFO
