spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: ''
    mode: LEGACYHTML5

  datasource:
    url: jdbc:mysql://localhost/tiple
    username: tiple
    password: tiple
    driverClassName: com.mysql.jdbc.Driver

logging:
  level:
    org:
      springframework:
        security: INFO
        web:      INFO
